MVCBlog/MVCBlog/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using SimpleForum.Models;

namespace SimpleForum.Models
{
    public class Category
    {
        public Category()
        {
            
        }
        public Category(string name)
        {
            this.Name = name;
            this.Posts = new HashSet<Post>();
        }

        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public virtual ICollection<Post> Posts { get; set; }
    }
}

MVCBlog/MVCBlog/Models/CategoryViewModel.cs
using SimpleForum.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCBlog.Models
{
    public class CategoryViewModel
    { 
        public CategoryViewModel()
        {
            this.Tags = new List<Tag>();
            this.Comments = new List<Comment>();
            this.Posts = new List<Post>();
        }

        public Category Category { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}

MVCBlog/MVCBlog/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcPaging;
using MVCBlog.Models;
using SimpleForum.Extensions;
using SimpleForum.Models;
using PagedList;

namespace SimpleForum.Controllers
{
    public class CategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categories
        [Authorize(Roles = "Administrators")]
        public ActionResult Index()
        {
            var category = db.Categories.ToList();
            return View(category);
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? page,int? id)
        {
            if (id == null)
            {
                this.AddNotification("Category cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index","Home");
            }

            var blogViewModels = new BlogViewModels();
            blogViewModels.Comments = db.Comments.Include((c => c.Author)).OrderByDescending(c => c.Date).Take(5).ToList();
            blogViewModels.Categories = db.Categories.ToList();
            blogViewModels.Tags = db.Tags.OrderByDescending(t => t.Posts.Count).Take(9).ToList();
            blogViewModels.Category = db.Categories.Find(id);
            var posts = db.Posts.Where(p => p.Category.Id == blogViewModels.Category.Id).ToList();
            blogViewModels.Posts = posts.OrderByDescending(p => p.Date).ToList();

            var pageNumber = page ?? 1;
            var onePageOfPosts = posts.ToPagedList(pageNumber, 2);
            ViewBag.onePageOfPosts = onePageOfPosts;

            if (blogViewModels.Category == null)
            {
                this.AddNotification("Category cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index","Home");
            }

            return View(blogViewModels);
        }

        // GET: Categories/Create
        [Authorize(Roles = "Administrators")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public ActionResult Create([Bind(Include = "Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                this.AddNotification("Category created", NotificationType.INFO);
                return RedirectToAction("Index", "Home");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                this.AddNotification("Category can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                this.AddNotification("Category can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public ActionResult Edit([Bind(Include = "Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                this.AddNotification("Category edited.", NotificationType.INFO);
                return RedirectToAction("Index", "Home");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                this.AddNotification("Category can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                this.AddNotification("Category can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            this.AddNotification("Category deleted", NotificationType.INFO);
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCBlog/MVCBlog/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcPaging;
using MVCBlog.Models;
using SimpleForum.Extensions;
using SimpleForum.Models;
using PagedList;

namespace MVCBlog.Controllers
{
    public class TagsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize(Roles = "Administrators")]
        // GET: Tags
        public ActionResult Index()
        {
            return View(db.Tags.ToList());
        }

        // GET: Tags/Details/5
        public ActionResult Details(int? page, int? id)
        {
            if (id == null)
            {
                this.AddNotification("Tag cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index");
            }

            var blogViewModels = new BlogViewModels();
            blogViewModels.Comments = db.Comments.Include((c => c.Author)).OrderByDescending(c => c.Date).Take(5).ToList();
            blogViewModels.Categories = db.Categories.ToList();
            blogViewModels.Tags = db.Tags.OrderByDescending(t => t.Posts.Count).Take(9).ToList();
            blogViewModels.Tag = db.Tags.Find(id);
            var posts = db.Posts.Where(p => p.Tags.Select(t => t.Id).Contains((int)id)).ToList();
            blogViewModels.Posts = posts.OrderByDescending(p => p.Date).ToList();

            var pageNumber = page ?? 1;
            var onePageOfPosts = posts.ToPagedList(pageNumber, 2);
            ViewBag.onePageOfPosts = onePageOfPosts;

            if (blogViewModels.Tag == null)
            {
                this.AddNotification("Tag cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index");
            }

            return View(blogViewModels);
        }

        // GET: Tags/Create
        [Authorize(Roles = "Administrators")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Tags/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public ActionResult Create([Bind(Include = "Id,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                this.AddNotification("Tag created", NotificationType.INFO);
                return RedirectToAction("Index","Home");
            }

            return View(tag);
        }

        // GET: Tags/Edit/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                this.AddNotification("Tag cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                this.AddNotification("Tag cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            return View(tag);
        }

        // POST: Tags/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Administrators")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                this.AddNotification("Tag edited.", NotificationType.INFO);
                return RedirectToAction("Index","Home");
            }
            return View(tag);
        }

        // GET: Tags/Delete/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                this.AddNotification("Tag cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                this.AddNotification("Tag cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            return View(tag);
        }

        // POST: Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            this.AddNotification("Tag deleted.", NotificationType.INFO);
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCBlog/MVCBlog/Views/Category/Create.cshtml
@model SimpleForum.Models.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCBlog/MVCBlog/Views/Category/Delete.cshtml
@model SimpleForum.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCBlog/MVCBlog/Views/Category/Details.cshtml
@using Microsoft.AspNet.Identity
@using MVCBlog.Models
@using SimpleForum.Models
@using PagedList.Mvc;
@using PagedList;
@using IPagedList = PagedList.IPagedList
@model MVCBlog.Models.BlogViewModels
<hr />
<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("New post", "Create", "Posts")</li>
</ol>
<hr />
<section id="blog" class="container-fluid">
    <div class="blog">
        <div class="row">
            <div class="col-md-8">
                @foreach (var post in ViewBag.onePageOfPosts)
                {
                    <div class="blog-item">
                        <div class="row">
                            <div class="col-xs-12 col-sm-2 text-center">
                                <div class="entry-meta">
                                    <span id="publish_date">@post.Date.ToString("dd MMM")</span>
                                    <span>
                                        @if (post.Author != null)
                                        {
                                            @: <strong>@post.Author.FullName</strong>
                                    }
                                        else
                                        {
                                            @: <strong>Annonymous</strong>
                                    }
                                    </span>
                                    <span><strong>@post.Comment.Count Comments</strong></span>
                                    <span><strong>56 Views</strong></span>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-10 blog-content">
                                @if (post.PostPicture != null)
                                {
                                    <img src="@Url.Action("Photo", "Posts", new {id = post.Id}, null)" width="100%" />
                                }
                                <h2>@Html.ActionLink((string)post.Title, "Details", "Posts", new { id = post.Id }, null)</h2>
                                <h3>@Html.Raw(post.Description)</h3>
                            </div>
                        </div>
                    </div>

                    <!--/.blog-item-->
                }
                <div class="pager">
                    @Html.PagedListPager((IPagedList)ViewBag.onePageOfPosts, page => Url.Action("Details", new { page }))
                </div>

            </div><!--/.col-md-8-->

            <aside class="col-md-4">

                <div class="widget categories">
                    <h3>Recent Comments</h3>
                    <div class="row">
                        <div class="single_comments">
                            @foreach (var comment in Model.Comments)
                            {
                                <div class="col-sm-2">
                                    @if (comment.Author != null && comment.Author.ProfilePicture != null)
                                    {
                                        <img src="@Url.Action("Photo", "Home", new {UserId = comment.Author.Id})" height="60" width="60" class="media-left" />
                                    }
                                    else
                                    {
                                        <img src="~/Content/avatar3.png" height="60" width="60" />
                                    }
                                </div>
                                <div class="col-sm-10">
                                    <p>@Utils.CutText(comment.Content, 35)</p>
                                    <div class="entry-meta small muted">
                                        <span>
                                            By
                                            @if (comment.Author != null)
                                            {
                                                @comment.Author.FullName
                                            }
                                            else
                                            {
                                                @:Anonnymous
                                                }
                                        </span>
                                        <span>
                                            <p>
                                                On @Html.ActionLink(Utils.CutText(comment.Post.Title, 30),
                                                           "Details", "Posts", new { id = comment.Post.Id }, null)
                                            </p>
                                        </span>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div><!--/.recent comments-->

                <div class="widget categories">
                    <h3>Categories</h3>
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="blog_category">
                                @foreach (var category in Model.Categories)
                                {
                                    <li>
                                        @Html.ActionLink(category.Name, "Details", "Category", new { id = category.Id }, null)
                                        <span class="badge">@category.Posts.Count</span>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div><!--/.categories-->


                <div class="widget tags">
                    <h3>Popular Tags</h3>
                    <ul class="tag-cloud">
                        @foreach (var tag in Model.Tags)
                        {
                            <li>
                                @Html.ActionLink(tag.Name, "Details", "Tags", new { id = tag.Id }, new { @class = "btn btn-xs btn-primary" })

                            </li>
                        }
                    </ul>
                </div><!--/.tags-->


            </aside>
        </div><!--/.row-->
    </div>
</section><!--/#blog-->
<!--/#bottom-->

MVCBlog/MVCBlog/Views/Category/Edit.cshtml
@model SimpleForum.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVCBlog/MVCBlog/Views/Category/Index.cshtml
@using SimpleForum.Models
@model IEnumerable<SimpleForum.Models.Category>

@{
    ViewBag.Title = "Index";
}

<h2>Categories</h2>
<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Name
        </th>
        <th class="text-center">
            Posts Count
        </th>
        <th class="align-right">
            Actions
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Posts.Count)
            </td>
            <td class="align-right">
                @Html.ActionLink("| Create |", "Create", "Category", new { id = item.Id }, null)
                @Html.ActionLink("Edit |", "Edit", "Category", new { id = item.Id }, null)
                @Html.ActionLink("Delete |", "Delete", "Category", new { id = item.Id }, null)
            </td>
        </tr>
    }
</table>