MVCBlog/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Net;
using Microsoft.Ajax.Utilities;
using MVCBlog.Models;
using PagedList;
using Microsoft.AspNet.Identity.Owin;
using MVCBlog.Extensions;
using MVCBlog.Models.DataModels;
using MVCBlog.Models.ViewModels;

namespace MVCBlog.Controllers
{
    [ValidateInput(false)]
    [Authorize(Roles = "Administrators")]
    public class AdminController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin
        public ActionResult Index()
        {
            var blogViewModels = new BlogViewModels();
            blogViewModels.Comments = db.Comments.ToList();
            blogViewModels.Categories = db.Categories.ToList();
            blogViewModels.Tags = db.Tags.ToList();
            blogViewModels.Posts = db.Posts.Include(p => p.Author).ToList();

            return View(blogViewModels);
        }

        // GET: Posts/Edit/5
        [Authorize]
        public ActionResult EditPost(int? id)
        {
            if (id == null)
            {
                this.AddNotification("Post cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index","Home");
            }

            Post post = db.Posts.Find(id);

            if (post == null)
            {
                this.AddNotification("Post cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index","Home");
            }

            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Tags = new MultiSelectList(db.Tags, "Id", "Name");
            ViewBag.Authors = db.Users.ToList();
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult EditPost([Bind(Include = "Id,Title,Body,Date,Description,Category_Id,Author_Id")] Post post, FormCollection form)
        {
            ViewBag.Categories = db.Categories.ToList();
            ViewBag.Tags = new MultiSelectList(db.Tags, "Id", "Name");
            ViewBag.Authors = db.Users.ToList();
            string selectedValues = form["Tags"];
            int[] id = null;
            if (selectedValues != null)
            {
                var tags = selectedValues.Split(',');
                id = tags.Select(int.Parse).ToArray();
            }
            if (ModelState.IsValid)
            {
                var item = db.Entry(post);
                item.State = EntityState.Modified;
                item.Collection(x => x.Tags).Load();
                if (selectedValues != null)
                {
                    post.Tags.Clear();
                    foreach (var tagid in id)
                    {
                        var tag = db.Tags.FirstOrDefault(t => t.Id == tagid);
                        post.Tags.Add(tag);
                    }
                }
                db.SaveChanges();
                this.AddNotification("Post edited.", NotificationType.INFO);    
                return RedirectToAction("Index");
            }
            return View(post);
        }

        // GET: Comments/Edit/5
        public ActionResult EditComment(int? id)
        {
            if (id == null)
            {
                this.AddNotification("Comment cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                this.AddNotification("Comment cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            ViewBag.PostId = new SelectList(db.Posts, "Id", "Title", comment.PostId);
            ViewBag.Authors = db.Users.ToList();
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditComment([Bind(Include = "Id,Content,PostId,Author_Id")] Comment comment)
        {
            if (User.IsInRole("Administrators") || User.Identity.Name == comment.Author.UserName)
            {
                if (ModelState.IsValid)
                {

                    db.Entry(comment).State = EntityState.Modified;
                    db.SaveChanges();
                    this.AddNotification("Comment edited", NotificationType.INFO);
                    return RedirectToAction("Index", "Home");
                }
                ViewBag.PostId = new SelectList(db.Posts, "Id", "Title", comment.PostId);
                ViewBag.Authors = db.Users.ToList();
                return View(comment);
            }
            this.AddNotification("You are not authorized.", NotificationType.ERROR);
            return RedirectToAction("Index", "Home");
        }

    }
}

MVCBlog/Controllers/CategoryController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using MVCBlog.Extensions;
using MVCBlog.Models;
using MVCBlog.Models.DataModels;
using MVCBlog.Models.ViewModels;
using PagedList;

namespace MVCBlog.Controllers
{
    public class CategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Categories
        [Authorize(Roles = "Administrators")]
        public ActionResult Index()
        {
            var category = db.Categories.ToList();
            return View(category);
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? page,int? id)
        {
            if (id == null)
            {
                this.AddNotification("Category cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index","Home");
            }

            var blogViewModels = new BlogViewModels();
            blogViewModels.Comments = db.Comments.Include((c => c.Author)).OrderByDescending(c => c.Date).Take(5).ToList();
            blogViewModels.Categories = db.Categories.ToList();
            blogViewModels.Tags = db.Tags.OrderByDescending(t => t.Posts.Count).Take(9).ToList();
            blogViewModels.Category = db.Categories.Find(id);
            var posts = db.Posts.Where(p => p.Category.Id == blogViewModels.Category.Id).ToList();
            blogViewModels.Posts = posts.OrderByDescending(p => p.Date).ToList();

            var pageNumber = page ?? 1;
            var onePageOfPosts = posts.ToPagedList(pageNumber, 2);
            ViewBag.onePageOfPosts = onePageOfPosts;

            if (blogViewModels.Category == null)
            {
                this.AddNotification("Category cant be found.", NotificationType.ERROR);
                return RedirectToAction("Index","Home");
            }

            return View(blogViewModels);
        }

        // GET: Categories/Create
        [Authorize(Roles = "Administrators")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public ActionResult Create([Bind(Include = "Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                this.AddNotification("Category created", NotificationType.INFO);
                return RedirectToAction("Index", "Home");
            }

            return View(category);
        }

        // GET: Categories/Edit/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                this.AddNotification("Category can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                this.AddNotification("Category can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public ActionResult Edit([Bind(Include = "Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                this.AddNotification("Category edited.", NotificationType.INFO);
                return RedirectToAction("Index", "Home");
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        [Authorize(Roles = "Administrators")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                this.AddNotification("Category can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                this.AddNotification("Category can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrators")]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            this.AddNotification("Category deleted", NotificationType.INFO);
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCBlog/Controllers/CommentsController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MVCBlog.Extensions;
using MVCBlog.Models;
using MVCBlog.Models.DataModels;

namespace MVCBlog.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize(Roles = "Administrators")]
        // GET: Comments
        public ActionResult Index()
        {   
            var comments = db.Comments.Include(c => c.Post);
            return View(comments.ToList());
        }

        [Authorize(Roles = "Administrators")]
        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            var authors = db.Posts.Include(p => p.Author);
            ViewBag.Authors = authors;
            if (id == null)
            {
                this.AddNotification("Comment can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                this.AddNotification("Comment can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            return View(comment);
        }

        [Authorize]
        // GET: Comments/Create
        public ActionResult Create()
        {
            return View();
        }
    
    
        
        [Authorize]
        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Content,PostId,Date")] Comment comment, int? id)
        {
            if (id == null)
            {
                this.AddNotification("Post can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                this.AddNotification("Post can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                comment.Post = post;
                comment.Author = db.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
                db.Comments.Add(comment);
                db.SaveChanges();
                this.AddNotification("Comment created", NotificationType.INFO);
                return RedirectToAction("Details", "Posts", new {id = post.Id});
            }
           
            return View(comment);
        }

        [Authorize]
        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {   
            if (id == null)
            {
                this.AddNotification("Comment can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            var comment = db.Comments.Include(p => p.Author).FirstOrDefault(p => p.Id == id);
            if (comment == null)
            {
                this.AddNotification("Comment can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index","Home");
            }
            if (User.IsInRole("Administrators") || User.Identity.Name == comment.Author.UserName)
            {
                return View(comment);
            }
            this.AddNotification("You are not authorized.", NotificationType.ERROR);
            return RedirectToAction("Index", "Home");
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Content")] Comment comment, int? id, int? postId)
        {
            Post post = db.Posts.Find(postId);

            if (ModelState.IsValid)
            {
                comment.PostId = post.Id;
                comment.Author_Id = User.Identity.GetUserId();
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                this.AddNotification("Comment edited", NotificationType.INFO);
                return RedirectToAction("Index", "Home");
            }
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                this.AddNotification("Comment can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            var comment = db.Comments.Include(p => p.Author).FirstOrDefault(p => p.Id == id);
            if (comment == null)
            {
                this.AddNotification("Comment can not be found.", NotificationType.ERROR);
                return RedirectToAction("Index", "Home");
            }
            if (User.IsInRole("Administrators") || User.Identity.Name == comment.Author.UserName)
            {
                return View(comment);
            }
            this.AddNotification("You are not authorized.", NotificationType.ERROR);
            return RedirectToAction("Index", "Home");
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var comment = db.Comments.Include(p => p.Author).FirstOrDefault(p => p.Id == id);
            if (User.IsInRole("Administrators") || User.Identity.Name == comment.Author.UserName)
            {
                db.Comments.Remove(comment);
                db.SaveChanges();
                this.AddNotification("Comment deleted", NotificationType.INFO);
                return RedirectToAction("Index", "Home");
            }
            this.AddNotification("You are not authorized.", NotificationType.ERROR);
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVCBlog/Views/Posts/Create.cshtml
@using System.Activities.Statements
@model MVCBlog.Models.DataModels.Post

@{
    ViewBag.Title = "Create";
}
<script>  document.querySelector('.editor').style.visibility = 'hidden';</script>
<h2>Create</h2>

@if (ViewBag.YouSelected != null)
{

    <div> You Selected:  @ViewBag.YouSelected</div>

}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="Category_Id" class="form-control">
                    @foreach (var item in ViewBag.Categories)
                    {
                        <option value="@item.Id">@item.Name</option>
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
        @Html.LabelFor(model => model.Tags, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.ListBox("Tags", ViewBag.Tags as MultiSelectList, new { @class = "chosen-container form-control" })
        </div>
    </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
<script type="text/javascript" src="~/Scripts/chosen.jquery.js"></script>
<script>
    $(".chosen-container ").chosen()
</script>
}

MVCBlog/Views/Posts/Details.cshtml
@using Microsoft.AspNet.Identity
@using MVCBlog.Models
@using PagedList.Mvc;
@using PagedList;
@using IPagedList = PagedList.IPagedList
@model MVCBlog.Models.ViewModels.PostViewModel
<hr />
<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("Reply", "Create", "Comments", new { id = Model.Post.Id }, null)</li>
    <li>@Html.ActionLink("New post", "Create", "Posts")</li>
    @if (User.IsInRole("Administrators") || User.Identity.Name == Model.Post.Author.UserName)
    {
        <li class="pull-right">@Html.ActionLink("Delete", "Delete", "Posts", new {id = Model.Post.Id}, null)</li>
        <li class="pull-right">@Html.ActionLink("Set Picture", "SetPicture", "Posts", new { id = Model.Post.Id }, null)</li>
        <li class="pull-right">@Html.ActionLink("Edit", "Edit", "Posts", new { id = Model.Post.Id }, null)</li>  
    }
</ol>
<hr />
<section id="blog" class="container-fluid">
    <div class="blog">
        <div class="row">
            <div class="col-md-8">
                <div class="blog-item">
                    <div class="row">
                        <div class="col-xs-12 col-sm-2 text-center">
                            <div class="entry-meta">
                                <span id="publish_date"><strong>@Model.Post.Date.ToString("dd MMM")</strong></span>
                                <span>
                                    @if (Model.Post.Author != null)
                                    {
                                        @: <strong>@Model.Post.Author.FullName</strong>
                                        }
                                    else
                                    {
                                        @:Annonymous
                                        }
                                </span>
                                <span>@Model.Post.Comment.Count Comments</span>
                                <span><strong>@Model.Post.Views views</strong></span>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-10 blog-content">
                            @if (Model.Post.PostPicture != null)
                            {
                                <img src="@Url.Action("Photo", "Posts", new {id = Model.Post.Id}, null)" width="100%" />
                            }
                            <h2>@Html.ActionLink(Model.Post.Title, "Details", "Posts", new {id = Model.Post.Id}, null)</h2>
                            <h3>@Html.Raw(Model.Post.Body)</h3>
                            <div class="post-tags">
                                @foreach (var tag in Model.Post.Tags)
                                {
                                   
                                    <span>@Html.ActionLink(tag.Name, "Details", "Tags", new { id = tag.Id }, new { @class="badge-default1" })</span>
                                }
                            </div>
                        </div>
                    </div>
                </div>
                <!--/.blog-item-->
                <h1 id="comments_title">@Model.Comments.Count Comments</h1>
                @foreach (var comment in ViewBag.onePageOfComments)
                {
                    <div class="media comment_section">
                        <div class="pull-left post_comments">
                            @if (comment.Author != null && comment.Author.ProfilePicture != null)
                            {
                                <img src="@Url.Action("Photo", "Home", new {UserId = comment.Author.Id})" height="60" width="60" class="media-left"/>
                            }
                            else
                            {
                                <img src="~/Content/avatar3.png" height="60" width="60"/>
                            }
                        </div>


                        @{
                            var commentAuthor = Model.Comments.FirstOrDefault(c => c.Author_Id == User.Identity.GetUserId());
                        }
                        @if (commentAuthor != null && (User.IsInRole("Administrators") || commentAuthor.Author_Id == User.Identity.GetUserId()))
                            {
                                <span>@Html.ActionLink("| Edit |", "Edit", "Comments", new { id = comment.Id, postId = Model.Post.Id }, null)</span>
                                    <span>@Html.ActionLink(" Delete |", "Delete", "Comments", new { id = comment.Id }, null)</span>
                            }
                        
                           
                        <div class="media-body post_reply_comments">
                            <h3>
                                @if (Model.Post.Author != null)
                                {
                                    @: @comment.Author.FullName
                                     }
                                else
                                {
                                    @:Annonymous
                                     }
                            </h3>
                            <h4>@comment.Date</h4>
                            <p>@Html.Raw(comment.Content)</p>
                        </div>
                    </div>
                }
                <div class="pager">
                    @Html.PagedListPager((IPagedList)ViewBag.onePageOfComments, page => Url.Action("Details", new { page }))
                </div>
            </div><!--/.col-md-8-->
            <aside class="col-md-4">

                <div class="widget categories">
                    <h3>Recent Comments</h3>
                    <div class="row">
                        <div class="single_comments">
                            @foreach (var comment in Model.CommentAside)
                            {
                                <div class="col-sm-2">
                                    @if (comment.Author != null && comment.Author.ProfilePicture != null)
                                    {
                                        <img src="@Url.Action("Photo", "Home", new {UserId = comment.Author.Id})" height="60" width="60" class="media-left" />
                                    }
                                    else
                                    {
                                        <img src="~/Content/avatar3.png" height="60" width="60" />
                                    }
                                </div>
                                <div class="col-sm-10">
                                    <p>@Utils.CutText(comment.Content, 35)</p>
                                    <div class="entry-meta small muted">
                                        <span>
                                            By
                                            @if (comment.Author != null)
                                            {
                                                @comment.Author.FullName
                                            }
                                            else
                                            {
                                                @:Anonnymous
                                                }
                                        </span>
                                        <span>
                                            <p>
                                                On @Html.ActionLink(Utils.CutText(comment.Post.Title, 30),
                                                       "Details", "Posts", new { id = comment.Post.Id }, null)
                                            </p>
                                        </span>
                                    </div>
                                </div>
                            }
                        </div>

                    </div>
                </div><!--/.recent comments-->

                <div class="widget categories">
                    <h3>Categories</h3>
                    <div class="row">
                        <div class="col-sm-6">
                            <ul class="blog_category">
                                @foreach (var category in Model.Categories)
                                {
                                    <li>
                                        @Html.ActionLink(category.Name, "Details", "Category", new { id = category.Id }, null)
                                        <span class="badge">@category.Posts.Count</span>
                                </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div><!--/.categories-->


                <div class="widget tags">
                    <h3>Popular Tags</h3>
                    <ul class="tag-cloud">
                        @foreach (var tag in Model.Tags)
                        {
                            <li>
                                @Html.ActionLink(tag.Name, "Details", "Tags", new { id = tag.Id }, new { @class = "btn btn-xs btn-primary" })

                            </li>
                        }
                    </ul>
                </div><!--/.tags-->
            </aside>
        </div><!--/.row-->
    </div>
</section><!--/#blog-->
<!--/#bottom-->

MVCBlog/Views/Posts/Index.cshtml
@model IEnumerable<MVCBlog.Models.DataModels.Post>

@{
    ViewBag.Title = "Index";
}

<h2>Posts</h2>
<table class="table">
    <tr>
        <th>
            Id
        </th>
        <th>
            Title
        </th>
        <th>
            Author
        </th>
        <th>
            Date
        </th>
        <th>
            Category
        </th>
        <th>
            Comments
        </th>
        <th>
            Tags
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.ActionLink(item.Title, "Details", "Posts", new { id = item.Id }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Comment.Count)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Tags.Count)
            </td>
            <td>
                @Html.ActionLink("Create |", "Create", "Posts", new { id = item.Id }, null)
                @Html.ActionLink("Edit |", "EditPost", "Admin", new { id = item.Id }, null)
                @Html.ActionLink("Details |", "Details", "Posts", new { id = item.Id }, null)
                @Html.ActionLink("Delete", "Delete", "Posts", new { id = item.Id }, null)
            </td>
        </tr>
    }
</table>